#!/usr/bin/env python

"""
Script to preprocess FreeSurfer surfaces for training
TopoFit models. If this code is useful to you, please cite:

TopoFit: Rapid Reconstruction of Topologically-Correct Cortical Surfaces
Andrew Hoopes, Juan Eugenio Iglesias, Bruce Fischl, Douglas Greve, Adrian Dalca
Medical Imaging with Deep Learning. 2022.
"""

import os
import argparse
import shutil
import surfa as sf
import topofit

parser = argparse.ArgumentParser()
parser.add_argument('subj', help='full path to recon-all FreeSurfer subject')
parser.add_argument('--avg', help='full path to recon-all FreeSurfer subject')
parser.add_argument('--rod', help='if you have read only access to data, limited space, and want to use the work around')
args = parser.parse_args()

    

# make sure FS has been sourced in the env
if shutil.which('mri_surf2surf') is None:
    sf.system.fatal('cannot find mri_surf2surf in system path, has freesurfer been sourced?')

fshome = os.environ.get('FREESURFER_HOME')
if fshome is None:
    sf.system.fatal('FREESURFER_HOME is not set in the env, has freesurfer been sourced?')

# set SUBJECTS_DIR manually based on path to input subject
if args.subj != None:
    subjects_dir = os.path.dirname(args.subj)
    os.environ['SUBJECTS_DIR'] = '/'#allows for usage of absolute paths, which is more flexible 

# make sure fsaverage is accessible from the SUBJECTS_DIR deprecated
if not os.path.exists(os.path.join(subjects_dir, 'fsaverage')):
    print(
        f'fsaverage subject does not exist in the base directory `{subjects_dir}`, '
         'so you must link it by running:\n\n'
        f'ln -s $FREESURFER_HOME/subjects/fsaverage {subjects_dir}/fsaverage\n')
    print('consider removing the final / from path to subject')
    if args.avg == None:
        args.avg = "$FREESURFER_HOME/subjects/fsaverage"
else:
    if args.avg == None:
        args.avg = os.path.join(subjects_dir, 'fsaverage')

print('args.avg after maniuplation', args.avg)
# compute talairach.xfm.lta if it doesn't exist
if args.rod is not None:
    #work around path for no write privileges
    id = args.subj.split('/')[-1]
    
    cmd = f'lta_convert --src {args.subj}/mri/orig.mgz ' \
            f'--trg {fshome}/average/mni305.cor.mgz --inxfm {args.subj}/mri/transforms/talairach.xfm ' \
            f'--outlta ltafiles/{id}.talairach.xfm.lta --subject {args.avg} --ltavox2vox'
    if sf.system.run(cmd) != 0:
        print('consider making ltafiles directory in base directory')
        sf.system.fatal('could not run lta_convert command')
elif not os.path.isfile(f'{args.subj}/mri/transforms/talairach.xfm.lta'):
    try:
        cmd = f'lta_convert --src {args.subj}/mri/orig.mgz ' \
            f'--trg {fshome}/average/mni305.cor.mgz --inxfm {args.subj}/mri/transforms/talairach.xfm ' \
            f'--outlta {args.subj}/mri/transforms/talairach.xfm.lta --subject {args.avg} --ltavox2vox'
        if sf.system.run(cmd) != 0:
            sf.system.fatal('could not run lta_convert command')
    except:
        print('you may want to create folder ltafiles in project base directory if you have read only access to your data')
# cycle through hemispheres

for i, hemi in enumerate(('lh', 'rh')):
    if args.rod is not None:#this path is for if you don't have write access to your data. it is messy, but will work. so shh. no duplicate ids.
        #s = ['..' for i in range(len(args.subj.split('/'))-2)]
        #s = '/'.join(s)
        id = args.subj.split('/')[-1]
        #os.environ['SUBJECTS_DIR'] = "/"#better hack than calculating how many ../
         
        cwd = os.getcwd()
        cmd = f'mri_surf2surf --mapmethod nnf --s {args.subj} --hemi {hemi} --sval-xyz white ' \
          f'--trgsubject {args.avg} --tval {cwd}/whiteicosurf/{id}.{hemi}.white.ico.surf ' \
          f'--tval-xyz {args.subj}/mri/norm.mgz'
        if sf.system.run(cmd) != 0:
            sf.system.fatal('could not run mri_surf2surf command')
    else:    
        try:
            # run the mesh resampling
            cmd = f'mri_surf2surf --mapmethod nnf --s {args.subj} --hemi {hemi} --sval-xyz white ' \
                f'--trgsubject {args.avg} --tval {args.subj}/surf/{hemi}.white.ico.surf ' \
                f'--tval-xyz {args.subj}/mri/norm.mgz'
            if sf.system.run(cmd) != 0:
                sf.system.fatal('could not run mri_surf2surf command')
        except:
            print('you may need to create directory whiteicosurf in your base directory if you have read only access to your data')
print('\nTopoFit preprocessing complete!')
