#!/bin/bash -p
. /opt/miniconda3/bin/activate topofit
#enter the command you would like to run below or modify this script to be more dynamic
#eg. /topofit/evaluate ...
#eg. /topofit/train ... 
#eg. /topofit/preprocess ...
#the following example requires --bind yourtopofitclone:/topofit/
/topofit/evaluate --subjs /data/users2/washbee/hcp-plis-subj/358144 --hemi lh --model /home/users/washbee1/projects/topofit/output/lh0475.pt
